#默认开发环境
spring:
  profiles.active: singleDev
---
#开发环境 
spring:
  profiles: singleDev
  datasource.url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS BRTLIC
  datasource.username: brtLic
  datasource.password: brtLic
  datasource.driver-class-name: org.h2.Driver
  
  application:
    name: notes
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  activiti.check-process-definitions: false
server:
  port: 9000
aaa: 1

